### ISSUE TITLE
_alternative:71: permission denied:

### ISSUE THREAD

**Issue by iahu** [chrisands/zsh-yarn-completions#5]
got an error message when I press `Tab` key under a workspace namespace.

e.g.
```sh
yw my-project | # press Tab key
```
```sh
yw my-project jest ./packages/a| # press Tab key
```

**Comment by chrisands** [comment]
`yw` is supposed to use like this `yw <workspace_name> jest` while in . 
But I'll try to look this week into errors. There shouldn't be an error in stdout.

**Comment by iahu** [comment]
Thanks your great work. do you have tracked this issuse ?

**Comment by chrisands** [comment]
Sorry, I didn't have time to look into it. I'll do this by the end of the week.

**Comment by iahu** [comment]
That’s great, thanks again.
